package com.mindfulEatingApp.mindfulEatingApp.dto.response;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import lombok.Getter; // Add Getter for the new field

@JsonDeserialize(builder = SignInResponse.Builder.class)
@Getter // Add Getter annotation to generate getters for all fields
public class SignInResponse {
    private final Long id;
    private final String username;
    private final String email;
    private final String message;
    private final String token; // <--- ADDED FIELD

    private SignInResponse(Builder builder) {
        this.id = builder.id;
        this.username = builder.username;
        this.email = builder.email;
        this.message = builder.message;
        this.token = builder.token; // <--- Assign new field
    }

    // Getters are now generated by Lombok's @Getter, no need for manual ones

    public static Builder builder() {
        return new Builder();
    }

    @JsonPOJOBuilder(withPrefix = "")
    public static class Builder {
        private Long id;
        private String username;
        private String email;
        private String message;
        private String token; // <--- ADDED FIELD

        public Builder id(Long id) {
            this.id = id;
            return this;
        }

        public Builder username(String username) {
            this.username = username;
            return this;
        }

        public Builder email(String email) {
            this.email = email;
            return this;
        }

        public Builder message(String message) {
            this.message = message;
            return this;
        }

        public Builder token(String token) { // <--- ADDED BUILDER METHOD
            this.token = token;
            return this;
        }

        public SignInResponse build() {
            return new SignInResponse(this);
        }
    }
}